/**
 * Facebook Ads click ID: fbclid
 * Capture on landing, persist in cookie, pass to Facebook for conversion attribution.
 * Docs: https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc
 */

const COOKIE_NAME = "buzzmove_facebook_ads";
const MAX_AGE_DAYS = 90; // Facebook recommends 90 days for fbclid

export interface FacebookAdsIds {
  fbclid?: string;
  fbp?: string; // Facebook browser ID (auto-generated by Pixel)
  fbc?: string; // Facebook click ID in _fbc cookie format
}

function getCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const match = document.cookie.match(
    new RegExp("(?:^|; )" + name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + "=([^;]*)")
  );
  return match ? decodeURIComponent(match[1]) : null;
}

function setCookie(name: string, value: string, maxAgeDays: number) {
  if (typeof document === "undefined") return;
  document.cookie = `${name}=${encodeURIComponent(value)}; path=/; max-age=${
    maxAgeDays * 24 * 60 * 60
  }; SameSite=Lax`;
}

/** Store fbclid. Call when URL has this param. */
export function storeFacebookAdsIds(ids: FacebookAdsIds): void {
  const filtered: FacebookAdsIds = {};
  if (ids.fbclid?.trim()) filtered.fbclid = ids.fbclid.trim();
  if (Object.keys(filtered).length === 0) return;
  setCookie(COOKIE_NAME, JSON.stringify(filtered), MAX_AGE_DAYS);
}

/** Read stored Facebook Ads click ID. Use when firing conversion events. */
export function getFacebookAdsIds(): FacebookAdsIds {
  const raw = getCookie(COOKIE_NAME);
  const ids: FacebookAdsIds = {};
  
  // Get fbclid from our custom cookie
  if (raw) {
    try {
      const parsed = JSON.parse(raw) as Record<string, string>;
      if (parsed.fbclid) ids.fbclid = parsed.fbclid;
    } catch {}
  }
  
  // Get _fbp (Facebook browser ID) from Facebook's own cookie
  const fbp = getCookie("_fbp");
  if (fbp) ids.fbp = fbp;
  
  // Get _fbc (Facebook click tracking) from Facebook's own cookie
  const fbc = getCookie("_fbc");
  if (fbc) ids.fbc = fbc;
  
  return ids;
}

/** Extract fbclid from URLSearchParams. */
export function extractFacebookAdsIdsFromParams(params: URLSearchParams): FacebookAdsIds {
  const fbclid = params.get("fbclid");
  const ids: FacebookAdsIds = {};
  if (fbclid) ids.fbclid = fbclid;
  return ids;
}

/** Build query string for success_url: ?fbclid=... */
export function toSuccessUrlParams(): string {
  const ids = getFacebookAdsIds();
  const parts: string[] = [];
  if (ids.fbclid) parts.push(`fbclid=${encodeURIComponent(ids.fbclid)}`);
  return parts.length > 0 ? parts.join("&") : "";
}

/**
 * Server-side: extract Facebook Ads IDs from cookies in request headers
 * Use in API routes or server components
 */
export function getFacebookAdsIdsFromCookies(cookieHeader: string | null): FacebookAdsIds {
  if (!cookieHeader) return {};

  const cookies = cookieHeader.split("; ");
  const ids: FacebookAdsIds = {};
  
  // Get fbclid from our custom cookie
  const adsCookie = cookies.find((c) => c.startsWith(`${COOKIE_NAME}=`));
  if (adsCookie) {
    try {
      const value = decodeURIComponent(adsCookie.substring(COOKIE_NAME.length + 1));
      const parsed = JSON.parse(value) as Record<string, string>;
      if (parsed.fbclid) ids.fbclid = parsed.fbclid;
    } catch {}
  }
  
  // Get _fbp from Facebook's cookie
  const fbpCookie = cookies.find((c) => c.startsWith("_fbp="));
  if (fbpCookie) {
    ids.fbp = decodeURIComponent(fbpCookie.substring(5));
  }
  
  // Get _fbc from Facebook's cookie
  const fbcCookie = cookies.find((c) => c.startsWith("_fbc="));
  if (fbcCookie) {
    ids.fbc = decodeURIComponent(fbcCookie.substring(5));
  }
  
  return ids;
}
