/**
 * Watermark service.
 * For MVP, we use a simple approach: store both watermarked and clean URLs.
 * The watermarked version is generated by Supabase Edge Function or
 * a simple server-side process.
 *
 * Production approach: Use FFmpeg to overlay watermark + downscale to 480p.
 * For now, we append a query parameter to differentiate and control access
 * via Supabase Storage policies.
 */

export interface WatermarkResult {
  cleanUrl: string;
  watermarkedUrl: string;
}

/**
 * Determines which video URL to serve based on user's plan.
 */
export function getVideoUrl(
  video: { output_video_url: string | null; output_video_watermarked_url: string | null },
  plan: string
): string | null {
  if (!video.output_video_url) return null;

  // Free users get watermarked version
  if (plan === "free" || !plan) {
    return video.output_video_watermarked_url || video.output_video_url;
  }

  // Paid users get clean version
  return video.output_video_url;
}

/**
 * Generate watermarked video URL path.
 * In production, this would trigger an FFmpeg job.
 * For MVP, we store the video in a "watermarked" subfolder.
 */
export function getWatermarkedPath(originalPath: string): string {
  const parts = originalPath.split("/");
  const filename = parts.pop();
  return [...parts, "watermarked", filename].join("/");
}
