-- Analytics reports generated by AI
create table if not exists analytics_reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  period_start timestamptz not null,
  period_end timestamptz not null,
  report_type text not null default 'daily',
  raw_data jsonb,
  report_content text not null
);

-- Index for listing reports by creation date
create index idx_analytics_reports_created_at on analytics_reports (created_at desc);

-- RLS: only service role can access
alter table analytics_reports enable row level security;
-- No RLS policies = only service_role key can access
